// Code Generated by Sidekick is for learning and experimentation purposes only. For other use cases, please see the guidance linked here for accessing and using the Deloitte-approved tools [GitHub Copilot](https://resources.deloitte.com/:p:/r/sites/MyTechnology/GenAI/Platforms_Tools/GitHub%20Copilot/GitHub_Copilot_Overview_Guide.pptx?d=w5099365971a946aaa49908583395b585&csf=1&web=1&e=I1r8Pf) or [AWS Codewhisperer](https://resources.deloitte.com/:p:/r/sites/MyTechnology/_layouts/15/Doc.aspx?sourcedoc=%7b5FA15CB2-2328-460F-8220-DC996136BAC5%7d&file=Amazon_CodeWhisperer_Overview_Guide.pptx&action=edit&mobileredirect=true).

import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { map, Observable } from 'rxjs';
import { Trainingselfie } from './trainingselfie.model';

@Injectable({
  providedIn: 'root'
})
export class TrainingselfieService {
  readonly baseUrl = 'https://localhost:7139/api';
  readonly serverBaseUrl = 'https://localhost:7139'; // Correct base URL for images

  constructor(private http: HttpClient) {}

  //fetch all training selfies
  TrainingselfieList(): Observable<Trainingselfie[]> {
    

    return this.http.get<Trainingselfie[]>(`${this.baseUrl}/TrainingSelfies`).pipe(
      map((data: Trainingselfie[]) =>
        data.map((TrainingS: Trainingselfie) => {
          // Replace backslashes with forward slashes
          const path = TrainingS.trainingImageUrl.replace(/\\/g, '/');
          // Encode only spaces and special characters
          const encodedPath = path.split('/').map(segment => encodeURIComponent(segment)).join('/');
          const constructedImageUrl = `${this.serverBaseUrl}${encodedPath}`;

          console.log('Constructed Profile Picture URL:', constructedImageUrl);

          return {
            ...TrainingS,
            trainingImageUrl: constructedImageUrl // Update trainingImageUrl with constructed URLs
          };
        })
      )
    );
  } 
   // Update an existing team selfie
  updateTrainingSelfie(id: number, formData: FormData): Observable<void> {
    return this.http.put<void>(`${this.baseUrl}/TrainingSelfies/${id}`, formData);
  }

  // Delete a team selfie
  deleteTrainingSelfie(id: number): Observable<void> {
    return this.http.delete<void>(`${this.baseUrl}/TrainingSelfies/${id}`);
  }
}


